title: US-RSE Community Syndicated Blog
description: Shared RSE experiences and stories
author: USRSE
baseurl: "/blog"
url: "https://usrse.github.io"

# Social Profiles
# twitter_username:  usrse
github_username:   usrse

# Paths
defaults:
    -
        scope:
            path: "pages"
            type: pages
        values:
            layout: page
    -
        scope:
            path: ""
            type: posts
        values:
            layout: post
            comments: true

# Navigation
navbar-links:
  Home: ""
  Community:
    - About: "about"
    - RSE Map: "map"
  Posts:
    - All Posts: "posts"
    - Archive: "archive"

# Build settings
permalink   : /:year/:categories/:title/
exclude: ["_site", "vendor", ".circleci"]

markdown:          kramdown
comments: true
paginate:          5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
